name: first

on: [push]

jobs:
  job1:
    name: job 1
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        uses: actions/checkout@v4
      - name: step 2
        run: echo $(date)

  job2:
    name: job 2
    runs-on: windows-latest
    steps:
      - name: step 1
        uses: actions/checkout@v4
      - name: step 2
        run: echo $(Get-Date)

  job3:
    name: job 3
    runs-on: macos-latest
    steps:
      - name: step 1
        uses: actions/checkout@v4
      - name: step 2
        run: echo $(date)

  job4:
    name: job 4
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: step 1
        uses: actions/checkout@v4
      - name: step 2
        run: echo "All jobs completed"
